name: Letterpress in NYC
favicon: null
layout_spectrum: 0.025561506394296885
typography_spectrum: 0.9639
title: Letterpress in NYC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
